### PR TITLE
cdnjs-importer 2.0.0

### LINKED ISSUE #8: Update is-there

### LINKED ISSUE #9: Use CLP as arguments parser
https://github.com/IonicaBizau/node-clp

### LINKED ISSUE #11: Support import from git repo

### LINKED ISSUE #12: Checkout a different branch

### PR DESCRIPTION
**Pull request by IonicaBizau**
- Relicensed under [The KINDLY License](https://github.com/IonicaBizau/kindly-license).
- Generated docs via [blah](https://github.com/IonicaBizau/node-blah).
- New cli interface, via [`clp`](https://github.com/IonicaBizau/node-clp). Fixed #9.
- Create a different branch from master when adding libraries. Fixes #12.
- Keep only one autoupdate field. Fixed #11.
- Updated dependencies. Fixed #8.

``` sh
$ cdnjs-importer -h
Usage: cdnjs-importer [options]

Options:
  -g, --git-url <git-url>  Your library git url.                   
  -p, --path <path>        The path to your cdnjs local repository.
  -h, --help               Displays this help.                     
  -v, --version            Displays version information.           

Examples:
  cdnjs-importer -g git@github.com:IonicaBizau/gh.js.git # adds gh.js to cdnjs
  cdnjs-importer -g ... -p path/to/cdnjs

The default cdnjs repository location is in ~/cdnjs

Documentation can be found at https://github.com/IonicaBizau/cdnjs-importer
```

### CODE REVIEW

**Comment by IonicaBizau** [comment]
@PeterDaveHello Could you please test it out? :smile:

**Comment by PeterDaveHello** [comment]
hmmmmmm ... I am afraid that I can not do it soon, but will do it after 2 weeks if you don't mind, currently working on some very important works, sorry.

**Comment by IonicaBizau** [comment]
> but will do it after 2 weeks if you don't mind

@PeterDaveHello So, could you test it out and give me feedback? :smile: I know time passes quickly. :hourglass:

**Comment by PeterDaveHello** [comment]
oooooooops, 3 more days please ... btw, would you like to move this project to cdnjs organization?

**Comment by IonicaBizau** [comment]
:smile: 

> btw, would you like to move this project to cdnjs organization?

@PeterDaveHello Sure! Maybe, can I get a little shiny donation? :grinning:

**Comment by PeterDaveHello** [comment]
@IonicaBizau What does the donation actually mean here bro?

**Comment by IonicaBizau** [comment]
@PeterDaveHello Some money on PayPal is always welcome! :smile_cat:

**Comment by PeterDaveHello** [comment]
Ha, I really hope so I can do, but actually, I don't even get any money from this project yet.
@thomasdavis, will our income from ads export to my account soon?

**Comment by PeterDaveHello** [comment]
`cdnjs-importer/bin/cdnjs-importer -g git://github.com/ocombe/ocLazyLoad.git`
Will not pass the test

**Comment by PeterDaveHello** [comment]
Can not handle(even let the user know) conflicts, would you like to fix it in this version or not?

**Comment by IonicaBizau** [comment]
> cdnjs-importer/bin/cdnjs-importer -g git://github.com/ocombe/ocLazyLoad.git
> Will not pass the test

I will check it out.

> Can not handle(even let the user know) conflicts, would you like to fix it in this version or not?

It's better to fix it now since this is major release.

**Comment by IonicaBizau** [comment]
@PeterDaveHello Why doesn't the above package pass the test?

**Comment by PeterDaveHello** [comment]
Which one? Do you have its dump?

**Comment by IonicaBizau** [comment]
@PeterDaveHello `cdnjs-importer/bin/cdnjs-importer -g git://github.com/ocombe/ocLazyLoad.git` -- don't have time to test it out, but having the error I can think where to fix it. :smile:

**Comment by PeterDaveHello** [comment]
I can not help without the dump, in fact, all the rules are in cdnjs's repo, you can check it out.

**Comment by IonicaBizau** [comment]
The test error says:

> Remove the first 2 spaces of each line and include blank line at end if you copy and paste this example

@PeterDaveHello I don't really understand why this appears -- I added the blank line at the end and removed the 2 spaces on each line, still, it appears. Why?

**Comment by PeterDaveHello** [comment]
How about give me the raw/bump to debug!

**Comment by IonicaBizau** [comment]
Okokok:

``` sh
·····································································································································································································································································
·····································································································································································································································································
·····································································································································································································································································
·····································································································································································································································································
·····································································································································································································································································
···············································································································································································································✗·····················································
·····································································································································································································································································
·····································································································································································································································································
·····································································································································································································································································
·····································································································································································································································································
·····································································································································································································································································
·····································································································································································································································································
·····································································································································································································································································
·····································································································································································································································································
·····································································································································································································································································
·····································································································································································································································································
·····································································································································································································································································
·····································································································································································································································································
·····································································································································································································································································
·····································································································································································································································································
·····································································································································································································································································
······················································································································································································································································               


    oclazyload                                                                                                                                                                                                                                                       
      ✗ oclazyload: format check                                                                                                                                                                                                                                     
        » oclazyload: package.json wrong format, correct one should be like this.                                                                                                                                                                                    
  (Remove the first 2 spaces of each line and include blank line at end if you copy and paste this example)                                                                                                                                                          
  {                                                                                                                                                                                                                                                                  
    "name": "oclazyload",                                                                                                                                                                                                                                            
    "version": "1.0.2",                                                                                                                                                                                                                                              
    "description": "Load modules on demand (lazy load) with angularJS",                                                                                                                                                                                              
    "main": "dist/ocLazyLoad.js",                                                                                                                                                                                                                                    
    "author": "Olivier Combe <olivier.combe@gmail.com>",                                                                                                                                                                                                             
    "license": "MIT",                                                                                                                                                                                                                                                
    "homepage": "https://github.com/ocombe/ocLazyLoad",                                                                                                                                                                                                              
    "directories": {                                                                                                                                                                                                                                                 
      "example": "examples"                                                                                                                                                                                                                                          
    },                                                                                                                                                                                                                                                               
    "repository": {                                                                                                                                                                                                                                                  
      "type": "git",                                                                                                                                                                                                                                                 
      "url": "git://github.com/ocombe/ocLazyLoad.git"                                                                                                                                                                                                                
    },                                                                                                                                                                                                                                                               
    "keywords": [                                                                                                                                                                                                                                                    
      "lazy load",                                                                                                                                                                                                                                                   
      "lazy-load",                                                                                                                                                                                                                                                   
      "load on demand",                                                                                                                                                                                                                                              
      "module",                                                                                                                                                                                                                                                      
      "angular",                                                                                                                                                                                                                                                     
      "angularJS"                                                                                                                                                                                                                                                    
    ],                                                                                                                                                                                                                                                               
    "bugs": {                                                                                                                                                                                                                                                        
      "url": "https://github.com/ocombe/ocLazyLoad/issues"                                                                                                                                                                                                           
    },                                                                                                                                                                                                                                                               
    "npmName": "oclazyload",                                                                                                                                                                                                                                         
    "npmFileMap": [                                                                                                                                                                                                                                                  
      {                                                                                                                                                                                                                                                              
        "basePath": "/dist",                                                                                                                                                                                                                                         
        "files": [                                                                                                                                                                                                                                                   
          "*/"                                                                                                                                                                                                                                                       
        ]                                                                                                                                                                                                                                                            
      }                                                                                                                                                                                                                                                              
    ],                                                                                                                                                                                                                                                               
    "filename": "modules"                                                                                                                                                                                                                                            
  }                                                                                                                                                                                                                                                                  

   // valid-packages-test.js:158                                                                                                                                                                                                                                     
  ✗ Broken » 14077 honored ∙ 1 broken (26.116s)                                                                                                                                                                                                                      
  npm ERR! Test failed.  See above for more details.                                                                                                                                                                                                                 
npm ERR! not ok code 0                              
```

**Comment by PeterDaveHello** [comment]
Could you give the dump of package.json?

**Comment by IonicaBizau** [comment]
``` json
$ cat ajax/libs/oclazyload/package.json                                                                                                                                                                                                   
{                                                                                                                                                                                                                                                                    
  "name": "oclazyload",                                                                                                                                                                                                                                              
  "version": "1.0.2",                                                                                                                                                                                                                                                
  "description": "Load modules on demand (lazy load) with angularJS",                                                                                                                                                                                                
  "main": "dist/ocLazyLoad.js",                                                                                                                                                                                                                                      
  "author": "Olivier Combe <olivier.combe@gmail.com>",                                                                                                                                                                                                               
  "license": "MIT",                                                                                                                                                                                                                                                  
  "homepage": "https://github.com/ocombe/ocLazyLoad",                                                                                                                                                                                                                
  "directories": {                                                                                                                                                                                                                                                   
    "example": "examples"                                                                                                                                                                                                                                            
  },                                                                                                                                                                                                                                                                 
  "repository": {                                                                                                                                                                                                                                                    
    "type": "git",                                                                                                                                                                                                                                                   
    "url": "git://github.com/ocombe/ocLazyLoad.git"                                                                                                                                                                                                                  
  },                                                                                                                                                                                                                                                                 
  "keywords": [                                                                                                                                                                                                                                                      
    "lazy load",                                                                                                                                                                                                                                                     
    "lazy-load",                                                                                                                                                                                                                                                     
    "load on demand",                                                                                                                                                                                                                                                
    "module",                                                                                                                                                                                                                                                        
    "angular",                                                                                                                                                                                                                                                       
    "angularJS"                                                                                                                                                                                                                                                      
  ],                                                                                                                                                                                                                                                                 
  "bugs": {                                                                                                                                                                                                                                                          
    "url": "https://github.com/ocombe/ocLazyLoad/issues"                                                                                                                                                                                                             
  },                                                                                                                                                                                                                                                                 
  "npmName": "oclazyload",                                                                                                                                                                                                                                           
  "npmFileMap": [                                                                                                                                                                                                                                                    
    {                                                                                                                                                                                                                                                                
      "basePath": "/dist",                                                                                                                                                                                                                                           
      "files": [                                                                                                                                                                                                                                                     
        "**/*"                                                                                                                                                                                                                                                       
      ]                                                                                                                                                                                                                                                              
    }                                                                                                                                                                                                                                                                
  ],                                                                                                                                                                                                                                                                 
  "filename": "modules"                                                                                                                                                                                                                                              
}                                                                                                                                                                                                                                                                    

```

**Comment by PeterDaveHello** [comment]
What's its md5 hash? c158f5f8b6375f1599ea86a86e0a158f? 59b6e9b10e03bef47986b9cf1df18adf?

**Comment by IonicaBizau** [comment]
@PeterDaveHello Hmm, how to calculate that hash?

``` sh
$ md5sum ~/cdnjs/ajax/libs/oclazyload/package.json
3acaff315b09a6d75e6a340f466670dd  /home/ionicabizau/cdnjs/ajax/libs/oclazyload/package.json
```

**Comment by PeterDaveHello** [comment]
Looks different, so I think you should better upload it to google drive or dropbox or somewhere else to let me download and test it, thanks!

**Comment by IonicaBizau** [comment]
Isn't this enough?

``` sh
$ cat ~/cdnjs/ajax/libs/oclazyload/package.json                                                                                                   
{
  "name": "oclazyload",
  "version": "1.0.2",
  "description": "Load modules on demand (lazy load) with angularJS",
  "main": "dist/ocLazyLoad.js",
  "author": "Olivier Combe <olivier.combe@gmail.com>",
  "license": "MIT",
  "homepage": "https://github.com/ocombe/ocLazyLoad",
  "directories": {
    "example": "examples"
  },
  "repository": {
    "type": "git",
    "url": "git://github.com/ocombe/ocLazyLoad.git"
  },
  "keywords": [
    "lazy load",
    "lazy-load",
    "load on demand",
    "module",
    "angular",
    "angularJS"
  ],
  "bugs": {
    "url": "https://github.com/ocombe/ocLazyLoad/issues"
  },
  "npmName": "oclazyload",
  "npmFileMap": [
    {
      "basePath": "/dist",
      "files": [
        "**/*"
      ]
    }
  ],
  "filename": "modules"
}

```

**Comment by PeterDaveHello** [comment]
No is not. You can try to copy and paste, I can't get the same md5.

**Comment by IonicaBizau** [comment]
@PeterDaveHello [There you go](https://www.dropbox.com/s/vwvy4bup18g17q6/package.json?dl=0)! :zap:

**Comment by PeterDaveHello** [comment]
hmmmm ... should remove the last blank line.

**Comment by IonicaBizau** [comment]
@PeterDaveHello Pushed a fix to pull first from `github/cdnjs/cdnjs` and then to add the files. Do you have any idea how to save the file without adding that new line at the end?

It's just a [`JSON.stringify`](https://github.com/IonicaBizau/node-w-json/blob/54adc28a1410f509f6e5c8daa4cc807fca373c20/lib/index.js#L23). On the other side, why is it so important not to have that new line at the end of the file (in cdnjs)?

**Comment by IonicaBizau** [comment]
Actually, it should end with a new line character. Why?

**Comment by PeterDaveHello** [comment]
We use JSON.stringify too, I think JSON.stringify didn't bite, see:

https://github.com/cdnjs/cdnjs/blob/master/auto-update.js#L185

``` js
        if (stable.is(version) && semver.gt(version, pkg.version)) {
          pkg.version = version;

          fs.writeFileSync(libPatha, JSON.stringify(pkg, null, 2) + '\n', 'utf8');
        }
```

https://github.com/cdnjs/autoupdate/blob/master/updaters/git.js#L60

``` js
            if(allFiles.length !==0 && stable.is(tag) && semver.gt(tag, package.version)){
              console.log('Updated package.json to version'.green, tag);
              var packagePath = path.normalize(path.join(__dirname, '../../cdnjs', 'ajax', 'libs', package.name, 'package.json')),
                packageJSON = JSON.parse(fs.readFileSync(packagePath, 'utf8'));
              packageJSON.version = tag;
              fs.writeFileSync(packagePath, JSON.stringify(packageJSON, undefined, 2)  + '\n');
            } 
```

We don't have to have a empty new line at the end of file, that doesn't make sense, some coding style even disallow it, and most of the libs don't do that, for examples:
https://github.com/jquery/jquery/blob/master/package.json
https://github.com/uikit/uikit/blob/master/package.json
https://github.com/angular/angular.js/blob/master/package.json
https://github.com/emberjs/ember.js/blob/master/package.json

**Comment by IonicaBizau** [comment]
> `fs.writeFileSync(libPatha, JSON.stringify(pkg, null, 2) + '\n', 'utf8');`

Exactly! So I need to handle that little `\n` in `w-json`. Will push a fix soon.

**Comment by IonicaBizau** [comment]
@PeterDaveHello Now it should work. The tests are passing. :smile:

**Comment by PeterDaveHello** [comment]
:+1:

**Comment by IonicaBizau** [comment]
@PeterDaveHello If you like, we can move it in @cdnjs. :tada: Got stable!

**Comment by xuhaotw** [comment]
@IonicaBizau Let's do it. We can discuss the detail on gitter :+1:

**Comment by PeterDaveHello** [comment]
@IonicaBizau Let's do it. We can discuss the detail on gitter :+1:

**Comment by IonicaBizau** [comment]
Hey @PeterDaveHello @Piicksarn @maruilian11! :sparkles: 

Could you please test these changes and give me feedback? I'm going to release the new version this week. :tada:

**Comment by PeterDaveHello** [comment]
hmmmm ... I need more time, working on other important issue right now.
I think we can release v2.0.0-betas right now.

**Comment by IonicaBizau** [comment]
@PeterDaveHello Good idea! `cdnjs-importer@2.0.0-beta` is out. :tada:

**Comment by PeterDaveHello** [comment]
Nice :+1: 

@ryankirkman: @IonicaBizau wanna post the info about the new version of importer on twitter, would you please help him? I have no permission on it~

**Comment by IonicaBizau** [comment]
@ryankirkman Yeah, an update would be welcome! :smile:

**Comment by ryankirkman** [comment]
Certainly gentlemen, here it is: https://twitter.com/cdnjs/status/650938062713688065

Thank you @IonicaBizau !

**Comment by PeterDaveHello** [comment]
@ryankirkman thanks

**Comment by IonicaBizau** [comment]
@ryankirkman @PeterDaveHello Thanks, guys! :sparkles:

Sorry it took so long to release the new version.

**Comment by PeterDaveHello** [comment]
@IonicaBizau no problem!

**Pull request merged**
